import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783102193741 implements MigrationInterface {
    name = 'InitialSchema1783102193741'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`game_providers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`prefix\` varchar(10) NOT NULL, \`logo\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_bed788a5bacd1547d345d37581\` (\`name\`), UNIQUE INDEX \`IDX_d30b26532a18117fb6e6f6a5b7\` (\`prefix\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`games\` (\`id\` int NOT NULL AUTO_INCREMENT, \`gameUUID\` varchar(255) NOT NULL, \`gameHumanReadableId\` varchar(255) NOT NULL, \`gameName\` varchar(255) NOT NULL, \`description\` text NULL, \`rules\` text NULL, \`status\` int NOT NULL DEFAULT '1', \`isActive\` tinyint NULL DEFAULT 1, \`provider_id\` int NOT NULL, \`thumbnail\` varchar(255) NOT NULL, \`marketingMaterialsZip\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`metaDataId\` int NULL, UNIQUE INDEX \`IDX_45014e2b1329da563f2fff0461\` (\`gameUUID\`), UNIQUE INDEX \`IDX_12bb3eef07a3bf81d6aa774b56\` (\`gameHumanReadableId\`), UNIQUE INDEX \`REL_e613c70c0a405148aa58df6c5e\` (\`metaDataId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`category_definitions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`key\` varchar(50) NOT NULL, \`label\` varchar(100) NOT NULL, \`color\` varchar(50) NOT NULL DEFAULT 'bg-gray-600', \`sortOrder\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2cdfcbd9625b1951c382077010\` (\`key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`game_categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`categories\` varchar(50) NOT NULL, \`gameId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`game_meta_data\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reelsWidth\` int NULL, \`reelsHeight\` int NULL, \`lines\` int NULL, \`marketing_materials\` varchar(255) NULL, \`supports_promo_freespins\` tinyint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`game_sessions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(255) NULL, \`playerId\` varchar(255) NOT NULL, \`isActive\` tinyint NULL, \`gameId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d99df7f0602e82327f4eb56ba4\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`favorite-games\` (\`id\` int NOT NULL AUTO_INCREMENT, \`playerId\` varchar(255) NOT NULL, \`gameUUID\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`country\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NULL, \`countryCode\` varchar(255) NULL, \`license\` varchar(255) NULL, \`language\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_723b232a5bfd0fc0c36973e59f\` (\`countryCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` varchar(36) NOT NULL, \`userName\` varchar(100) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(20) NULL, \`password\` varchar(255) NOT NULL, \`firstName\` varchar(100) NOT NULL, \`lastName\` varchar(100) NOT NULL, \`countryId\` int NULL, \`xp\` int NOT NULL DEFAULT '0', \`citizenship\` varchar(100) NULL, \`birthday\` date NOT NULL, \`verified\` tinyint NULL DEFAULT 0, \`personalId\` varchar(50) NULL, \`isBlocked\` tinyint NOT NULL DEFAULT 0, \`blockReason\` varchar(500) NULL, \`resetToken\` varchar(128) NULL, \`resetTokenExpiresAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_user\` (\`id\`), UNIQUE INDEX \`IDX_da5934070b5f2726ebfd3122c8\` (\`userName\`), UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), UNIQUE INDEX \`IDX_8e1f623798118e629b46a9e629\` (\`phone\`), UNIQUE INDEX \`IDX_9acd140c7131c76a02981b4138\` (\`personalId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_session\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(255) NULL, \`ip\` varchar(255) NULL, \`userId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`expiresAt\` datetime NOT NULL, UNIQUE INDEX \`IDX_b330b1d48bb9384e7f4b8efbc0\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user-verify\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` varchar(255) NOT NULL, \`otp\` varchar(6) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`expiresAt\` datetime NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user-levels\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`minPoints\` int NOT NULL, \`maxPoints\` int NOT NULL, \`order\` int NOT NULL DEFAULT '0', \`description\` varchar(255) NULL, \`badgeUrl\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`wallet\` (\`id\` varchar(36) NOT NULL, \`balance\` int NOT NULL DEFAULT '0', \`currency\` varchar(255) NOT NULL, \`userId\` varchar(36) NULL, UNIQUE INDEX \`REL_35472b1fe48b6330cd34970956\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bonus-wallet\` (\`id\` varchar(36) NOT NULL, \`bonus\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_wagering_stats\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`totalDeposits\` bigint NOT NULL DEFAULT '0', \`totalWithdrawals\` bigint NOT NULL DEFAULT '0', \`totalDebit\` bigint NOT NULL DEFAULT '0', \`totalCredit\` bigint NOT NULL DEFAULT '0', \`totalWagered\` bigint NOT NULL DEFAULT '0', \`netProfit\` bigint NOT NULL DEFAULT '0', \`rtp\` decimal(5,2) NOT NULL DEFAULT '0.00', \`bonusBetsCount\` int NOT NULL DEFAULT '0', \`bonusWinnings\` bigint NOT NULL DEFAULT '0', \`todayWagered\` bigint NOT NULL DEFAULT '0', \`weeklyWagered\` bigint NOT NULL DEFAULT '0', \`monthlyWagered\` bigint NOT NULL DEFAULT '0', \`lastActivityDate\` timestamp NULL, \`lastResetDate\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_4021be3a815d16bcedeee3e0a5\` (\`userId\`), UNIQUE INDEX \`REL_4021be3a815d16bcedeee3e0a5\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_promotions\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(36) NOT NULL, \`promotionId\` varchar(36) NOT NULL, \`status\` enum ('assigned', 'active', 'completed', 'expired', 'cancelled') NOT NULL DEFAULT 'assigned', \`bonusBalance\` bigint NOT NULL DEFAULT '0', \`wageringRequired\` bigint NOT NULL DEFAULT '0', \`wageringCompleted\` bigint NOT NULL DEFAULT '0', \`activatedAt\` timestamp NULL, \`expiresAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_user_promo_pair\` (\`userId\`, \`promotionId\`), INDEX \`idx_user_promo_user_status\` (\`userId\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promotion_audit_log\` (\`id\` varchar(36) NOT NULL, \`action\` enum ('created', 'updated', 'assigned', 'activated', 'credited', 'completed', 'expired', 'cancelled') NOT NULL, \`promotionId\` varchar(36) NULL, \`userId\` varchar(36) NULL, \`performedBy\` varchar(255) NULL, \`metadata\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_audit_user\` (\`userId\`), INDEX \`idx_audit_promo\` (\`promotionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admins\` (\`id\` varchar(36) NOT NULL, \`username\` varchar(100) NOT NULL, \`password\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`firstName\` varchar(100) NULL, \`lastName\` varchar(100) NULL, \`role\` enum ('super_admin', 'admin', 'moderator') NOT NULL DEFAULT 'moderator', \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4ba6d0c734d53f8e1b2e24b6c5\` (\`username\`), UNIQUE INDEX \`IDX_051db7d37d478a69a7432df147\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_sessions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(255) NULL, \`ip\` varchar(255) NULL, \`adminId\` varchar(255) NOT NULL, \`adminRole\` enum ('super_admin', 'admin', 'moderator') NOT NULL DEFAULT 'moderator', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`expiresAt\` datetime NOT NULL, UNIQUE INDEX \`IDX_9412db96e8933fd0c58fdbf0b2\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`name\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`description\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`type\` enum ('welcome', 'no_deposit', 'free_spins', 'reload', 'cashback', 'high_roller', 'loyalty', 'tournament', 'birthday', 'referral', 'no_wager') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`status\` enum ('draft', 'active', 'paused', 'archived') NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`rewardType\` enum ('bonus_balance', 'real_balance', 'free_spins') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`rewardValue\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`wageringMultiplier\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`gameWeights\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`triggerCondition\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`targetAudience\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`maxWithdrawal\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`maxUsagePerUser\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`validityHours\` int NOT NULL DEFAULT '72'`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`freeSpinsGameIds\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`freeSpinsBetAmount\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`userChoosesGame\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`eligibleCategories\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`allowedGameUUIDs\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`startDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`endDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`promotions\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`idx_game_id\` ON \`transactions\` (\`game_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_promo_status_type\` ON \`promotions\` (\`status\`, \`type\`)`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_e613c70c0a405148aa58df6c5e2\` FOREIGN KEY (\`metaDataId\`) REFERENCES \`game_meta_data\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_6f24aded90e1f9717355239c826\` FOREIGN KEY (\`provider_id\`) REFERENCES \`game_providers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_categories\` ADD CONSTRAINT \`FK_7f79df7fcb94cbb3415e0cb6750\` FOREIGN KEY (\`gameId\`) REFERENCES \`games\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorite-games\` ADD CONSTRAINT \`FK_68a613538ff1bf4e70143b6b60e\` FOREIGN KEY (\`gameUUID\`) REFERENCES \`games\`(\`gameUUID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_4aaf6d02199282eb8d3931bff31\` FOREIGN KEY (\`countryId\`) REFERENCES \`country\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wallet\` ADD CONSTRAINT \`FK_35472b1fe48b6330cd349709564\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_e9acc6efa76de013e8c1553ed2b\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_20492232b7f3acb3ef924fa92a7\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`gameUUID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_wagering_stats\` ADD CONSTRAINT \`FK_4021be3a815d16bcedeee3e0a51\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_promotions\` ADD CONSTRAINT \`FK_97451e00599a75f4d278179c8e0\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_promotions\` ADD CONSTRAINT \`FK_9013afb6178e900584cbcfb24f8\` FOREIGN KEY (\`promotionId\`) REFERENCES \`promotions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_promotions\` DROP FOREIGN KEY \`FK_9013afb6178e900584cbcfb24f8\``);
        await queryRunner.query(`ALTER TABLE \`user_promotions\` DROP FOREIGN KEY \`FK_97451e00599a75f4d278179c8e0\``);
        await queryRunner.query(`ALTER TABLE \`user_wagering_stats\` DROP FOREIGN KEY \`FK_4021be3a815d16bcedeee3e0a51\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_20492232b7f3acb3ef924fa92a7\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_e9acc6efa76de013e8c1553ed2b\``);
        await queryRunner.query(`ALTER TABLE \`wallet\` DROP FOREIGN KEY \`FK_35472b1fe48b6330cd349709564\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_4aaf6d02199282eb8d3931bff31\``);
        await queryRunner.query(`ALTER TABLE \`favorite-games\` DROP FOREIGN KEY \`FK_68a613538ff1bf4e70143b6b60e\``);
        await queryRunner.query(`ALTER TABLE \`game_categories\` DROP FOREIGN KEY \`FK_7f79df7fcb94cbb3415e0cb6750\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_6f24aded90e1f9717355239c826\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_e613c70c0a405148aa58df6c5e2\``);
        await queryRunner.query(`DROP INDEX \`idx_promo_status_type\` ON \`promotions\``);
        await queryRunner.query(`DROP INDEX \`idx_game_id\` ON \`transactions\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`endDate\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`startDate\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`allowedGameUUIDs\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`eligibleCategories\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`userChoosesGame\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`freeSpinsBetAmount\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`freeSpinsGameIds\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`validityHours\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`maxUsagePerUser\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`maxWithdrawal\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`targetAudience\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`triggerCondition\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`gameWeights\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`wageringMultiplier\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`rewardValue\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`rewardType\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`promotions\` DROP COLUMN \`name\``);
        await queryRunner.query(`DROP INDEX \`IDX_9412db96e8933fd0c58fdbf0b2\` ON \`admin_sessions\``);
        await queryRunner.query(`DROP TABLE \`admin_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_051db7d37d478a69a7432df147\` ON \`admins\``);
        await queryRunner.query(`DROP INDEX \`IDX_4ba6d0c734d53f8e1b2e24b6c5\` ON \`admins\``);
        await queryRunner.query(`DROP TABLE \`admins\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_promo\` ON \`promotion_audit_log\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_user\` ON \`promotion_audit_log\``);
        await queryRunner.query(`DROP TABLE \`promotion_audit_log\``);
        await queryRunner.query(`DROP INDEX \`idx_user_promo_user_status\` ON \`user_promotions\``);
        await queryRunner.query(`DROP INDEX \`idx_user_promo_pair\` ON \`user_promotions\``);
        await queryRunner.query(`DROP TABLE \`user_promotions\``);
        await queryRunner.query(`DROP INDEX \`REL_4021be3a815d16bcedeee3e0a5\` ON \`user_wagering_stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_4021be3a815d16bcedeee3e0a5\` ON \`user_wagering_stats\``);
        await queryRunner.query(`DROP TABLE \`user_wagering_stats\``);
        await queryRunner.query(`DROP TABLE \`bonus-wallet\``);
        await queryRunner.query(`DROP INDEX \`REL_35472b1fe48b6330cd34970956\` ON \`wallet\``);
        await queryRunner.query(`DROP TABLE \`wallet\``);
        await queryRunner.query(`DROP TABLE \`user-levels\``);
        await queryRunner.query(`DROP TABLE \`user-verify\``);
        await queryRunner.query(`DROP INDEX \`IDX_b330b1d48bb9384e7f4b8efbc0\` ON \`user_session\``);
        await queryRunner.query(`DROP TABLE \`user_session\``);
        await queryRunner.query(`DROP INDEX \`IDX_9acd140c7131c76a02981b4138\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e1f623798118e629b46a9e629\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_da5934070b5f2726ebfd3122c8\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`idx_user\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_723b232a5bfd0fc0c36973e59f\` ON \`country\``);
        await queryRunner.query(`DROP TABLE \`country\``);
        await queryRunner.query(`DROP TABLE \`favorite-games\``);
        await queryRunner.query(`DROP INDEX \`IDX_d99df7f0602e82327f4eb56ba4\` ON \`game_sessions\``);
        await queryRunner.query(`DROP TABLE \`game_sessions\``);
        await queryRunner.query(`DROP TABLE \`game_meta_data\``);
        await queryRunner.query(`DROP TABLE \`game_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_2cdfcbd9625b1951c382077010\` ON \`category_definitions\``);
        await queryRunner.query(`DROP TABLE \`category_definitions\``);
        await queryRunner.query(`DROP INDEX \`REL_e613c70c0a405148aa58df6c5e\` ON \`games\``);
        await queryRunner.query(`DROP INDEX \`IDX_12bb3eef07a3bf81d6aa774b56\` ON \`games\``);
        await queryRunner.query(`DROP INDEX \`IDX_45014e2b1329da563f2fff0461\` ON \`games\``);
        await queryRunner.query(`DROP TABLE \`games\``);
        await queryRunner.query(`DROP INDEX \`IDX_d30b26532a18117fb6e6f6a5b7\` ON \`game_providers\``);
        await queryRunner.query(`DROP INDEX \`IDX_bed788a5bacd1547d345d37581\` ON \`game_providers\``);
        await queryRunner.query(`DROP TABLE \`game_providers\``);
    }

}
